# Generated by Django 4.2.3 on 2023-07-20 12:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_myfileupload_my_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='myfileupload',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.bidgely'),
        ),
    ]
